
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 20;
  public static final int NUMERO = 31;
  public static final int EXTRA = 15;
  public static final int TIPO = 11;
  public static final int UNIR = 10;
  public static final int PIE = 4;
  public static final int DOS_PUNTOS = 29;
  public static final int PORCENTAJE = 13;
  public static final int CORCHETE_C = 24;
  public static final int ETIQUETAS = 8;
  public static final int CORCHETE_A = 23;
  public static final int LLAVE_C = 26;
  public static final int LLAVE_A = 25;
  public static final int IDENTIFICADOR = 33;
  public static final int BARRAS = 3;
  public static final int TITULO = 5;
  public static final int PUNTO_COMA = 28;
  public static final int EOF = 0;
  public static final int DECIMAL = 32;
  public static final int VALORES = 9;
  public static final int error = 1;
  public static final int COMILLA = 27;
  public static final int COMA = 34;
  public static final int COMENTARIO = 30;
  public static final int EJE_Y = 7;
  public static final int MENOS = 18;
  public static final int EJE_X = 6;
  public static final int ERROR = 35;
  public static final int TOTAL = 14;
  public static final int PARENTESIS_C = 22;
  public static final int PARENTESIS_A = 21;
  public static final int CANTIDAD = 12;
  public static final int DEF = 2;
  public static final int ALMOHADILLA = 19;
  public static final int EJECUTAR = 16;
  public static final int MAS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJE_X",
  "EJE_Y",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "MAS",
  "MENOS",
  "ALMOHADILLA",
  "DIAGONAL",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "LLAVE_A",
  "LLAVE_C",
  "COMILLA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "COMENTARIO",
  "NUMERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "COMA",
  "ERROR"
  };
}

